[tool.poetry]
name = "pockvoc"
version = "0.1.0"
description = ""
authors = ["Hetorus NL <timkleinnijenhuis@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
black = "^23.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
